baseURL = "https://LazyYuuki.github.io/"
defaultContentLanguage = "en"
languageCode = "en"
title = "The Lazy Blog"
theme = "DoIt"


[params]
# DoIt theme version
version = "0.4.0"
dateFormat = "Jan 02, 2006"
defaultTheme = "dark"
description = "A blog about all thing engineering and startup related"
enablePWA = true
fingerprint = "sha256"
images = ["/avatar.png"]
keywords = [
  "ai",
  "artificial intelligence",
  "business",
  "cloud",
  "code",
  "engineer",
  "engineering",
  "large language model",
  "llm",
  "llmops",
  "machine learning",
  "ml",
  "mlops",
  "programming",
  "saas",
  "software",
  "start-up",
]
license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'
optimizeImages = true
cacheRemoteImages = true

# Author config
[params.author]
name = "Lazy Yuuki"
avatar = "/avatar.png"

[params.app]
title = "The Lazy Blog"
noFavicon = false

[params.search]
enable = true
type = "fuse"
contentLength = 4000
highlightTag = "em"
maxResultLength = 10
placeholder = "Keywords to search for..."

[params.search.fuse]
# DoIt NEW | 0.2.12 https://fusejs.io/api/options.html
isCaseSensitive = false
minMatchCharLength = 2
findAllMatches = false
location = 0
threshold = 0.3
distance = 100
ignoreLocation = false
useExtendedSearch = false
ignoreFieldNorm = false

[params.image]
cacheRemote = true
optimize = true

[params.header]
themeChangeMode = "switch"

[params.header.title]
name = "The Lazy Blog"
post = "😴"

[params.footer]
enable = true
hugo = true
author = true
since = 2024
license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

[params.section]
paginate = 20
dateFormat = "Jan 02"
rss = 5

[params.section.recentlyUpdated]
enable = true
rss = true
days = 30
maxCount = 5

[params.list]
paginate = 20
dateFormat = "Jan 02"
rss = 5

[params.home]
rss = 10

[params.home.profile]
enable = true
avatarURL = "/avatar.png"
title = "Lazy, but not too lazy"
subtitle = "Welcome to my humble blog"
typeit = true
social = true

[params.home.posts]
enable = true
paginate = 5

[params.social]
BuyMeACoffee = "https://buymeacoffee.com/lazyyuuki"
Github = "https://github.com/LazyYuuki"
Linkedin = "www.linkedin.com/in/buiquanghuy"
Youtubechannel = "xxxx"
RSS = true

[params.page]
seriesNavigation = true
enableLastMod = true
enableWordCount = true
enableReadingTime = true

[params.page.outdatedArticleReminder]
enable = false

[params.page.toc]
enable = false
keepStatic = false
auto = true

[params.page.math]
enable = true
# default block delimiter is $$ ... $$ and \\[ ... \\]
blockLeftDelimiter = ""
blockRightDelimiter = ""
# default inline delimiter is $ ... $ and \\( ... \\)
inlineLeftDelimiter = ""
inlineRightDelimiter = ""
copyTex = true
mhchem = true

[params.page.code]
maxShownLines = 10
copy = true

[params.page.table]
sort = true

[params.page.mapbox]

[params.page.share]
enable = true
Facebook = true
HackerNews = true
Instapaper = true
Linkedin = true
Mastodon = true
Pocket = true
Reddit = true
Twitter = true
Whatsapp = true

[params.page.instantpage]
enable = true

[params.page.comment]
enable = true

[params.page.comment.disqus]
enable = false
shortname = "lazyblog-1"

# Third-party library config
[params.page.library.css]
fontsize = "font-size.css"

[params.page.library.js]

[params.page.seo]

[params.page.related]
enable = true
count = 3

[params.sponsor]
enable = true
bio = "Sponsor me to yap more!"
link = "https://buymeacoffee.com/lazyyuuki"

[params.typeit]
speed = 50         # in ms
cursorSpeed = 1000
cursorChar = "█"
duration = -1

[params.verification]
google = ""

[params.seo]
alternateName = ["Lazy Blog", "LazyYuuki", "LazyYuuki's blog", "The Lazy Blog"]

[params.analytics]

[params.cookieconsent]
enable = false

[markup]
# Syntax Highlighting
[markup.highlight]
codeFences = true
guessSyntax = true
lineNos = true
lineNumbersInTable = true
noClasses = false

[markup.goldmark]
[markup.goldmark.extensions]
definitionList = true
footnote = true
linkify = true
strikethrough = true
table = true
taskList = true
typographer = true

[markup.goldmark.renderer]
unsafe = true

[markup.tableOfContents]
startLevel = 1
endLevel = 6

[outputs]
home = ["HTML", "JSON", "RSS"]
page = ["HTML", "MarkDown"]
section = ["HTML", "RSS"]
taxonomy = ["HTML", "RSS"]

[taxonomies]
series = 'series'
tag = 'tags'

[menu]
[[menu.main]]
identifier = "posts"
pre = "📝"
name = "Posts"
url = "/posts/"
weight = 1

[[menu.main]]
identifier = "quotes"
pre = "📜"
name = "Quotes"
url = "/quotes/"
title = "Quotes that I like"
weight = 2

[[menu.main]]
identifier = "lists"
pre = "📓"
name = "My Lists"
url = "/lists/"
title = "A list of list of things in my life"
weight = 3

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 4

[[menu.main]]
identifier = "series"
name = "Series"
url = "/series/"
weight = 4

[[menu.main]]
identifier = "about"
name = "About me"
url = "/about/"
